### ISSUE TITLE
Error Keeps Popping Up, Don't Know Why

### ISSUE THREAD

**Issue by benmbrennan** [robertdkirkby/getfreddata-matlab#1]
Output argument "val" (and maybe others) not assigned during call to "getFredData>getValue".

Are these functions just busted?  Every time I try to use them Matlab also crashes like 5 minutes later.

**Comment by robertdkirkby** [comment]
They should work fine, I use them most days without issue (I know numerous other people who also use them without error). Could you please post example code that generates this error?

(Sorry for delayed response, was off traveling for past two weeks)

**Comment by robertdkirkby** [comment]
Closed as over a month without response. Since it remains undocumented I am assuming error was not caused by getFredData itself.
